// <auto-generated />
using System;
using Aoun.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aoun.Migrations
{
    [DbContext(typeof(AounDbContext))]
    [Migration("20260305201332_AddAccidentConflicts")]
    partial class AddAccidentConflicts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aoun.Models.Accident", b =>
                {
                    b.Property<int>("AccidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccidentId"));

                    b.Property<DateOnly?>("AccidentDate")
                        .HasColumnType("date")
                        .HasColumnName("accident_date");

                    b.Property<TimeOnly?>("AccidentTime")
                        .HasColumnType("time")
                        .HasColumnName("accident_time");

                    b.Property<string>("AccidentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accident_type");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("AccidentId")
                        .HasName("PK__Accident__A27CA62BCAA43B20");

                    b.ToTable("Accident");
                });

            modelBuilder.Entity("Aoun.Models.AccidentConflict", b =>
                {
                    b.Property<int>("AccidentConflictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccidentConflictId"));

                    b.Property<int>("AccidentId")
                        .HasColumnType("int");

                    b.Property<string>("ConflictType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccidentConflictId");

                    b.HasIndex("AccidentId", "ConflictType")
                        .IsUnique();

                    b.ToTable("AccidentConflicts");
                });

            modelBuilder.Entity("Aoun.Models.AccidentReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("AccidentId")
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("approval_status");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("FaultPercentDriver1")
                        .HasColumnType("int")
                        .HasColumnName("fault_percent_driver1");

                    b.Property<int?>("FaultPercentDriver2")
                        .HasColumnType("int")
                        .HasColumnName("fault_percent_driver2");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pdf_path");

                    b.Property<string>("Summary")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("summary");

                    b.HasKey("ReportId")
                        .HasName("PK__Accident__779B7C58890D5B1E");

                    b.HasIndex(new[] { "AccidentId" }, "UQ__Accident__A27CA62AE269DDD4")
                        .IsUnique();

                    b.ToTable("Accident_Report");
                });

            modelBuilder.Entity("Aoun.Models.AccidentSessionParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccidentId")
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Waiting")
                        .HasColumnName("current_step");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("int")
                        .HasColumnName("driver_user_id");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsJoined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_joined");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("AccidentId");

                    b.ToTable("AccidentSessionParticipants", (string)null);
                });

            modelBuilder.Entity("Aoun.Models.Answer", b =>
                {
                    b.Property<int>("AccidentId")
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("int")
                        .HasColumnName("driver_user_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("AnsweredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("answered_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("FreeText")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("free_text");

                    b.Property<string>("Response")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("response");

                    b.Property<string>("SelectedOptionCode")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("selected_option_code");

                    b.HasKey("AccidentId", "DriverUserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer", (string)null);
                });

            modelBuilder.Entity("Aoun.Models.Driver", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("driver_name");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("license_number");

                    b.HasKey("UserId")
                        .HasName("PK__Driver__...");

                    b.HasIndex(new[] { "LicenseNumber" }, "UQ__Driver__D482A0036CD618F0")
                        .IsUnique();

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("Aoun.Models.DriverFeedback", b =>
                {
                    b.Property<int>("AccidentId")
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("int")
                        .HasColumnName("driver_user_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("FeedbackDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("feedback_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SatisfactionLevel")
                        .HasColumnType("int")
                        .HasColumnName("satisfaction_level");

                    b.HasKey("AccidentId", "DriverUserId");

                    b.HasIndex("DriverUserId");

                    b.ToTable("Driver_Feedback");
                });

            modelBuilder.Entity("Aoun.Models.Image", b =>
                {
                    b.Property<int>("AccidentId")
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int?>("DriverUserId")
                        .HasColumnType("int")
                        .HasColumnName("driver_user_id");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_path");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("upload_date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AccidentId", "ImageId");

                    b.HasIndex("DriverUserId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Aoun.Models.Involve", b =>
                {
                    b.Property<int>("AccidentId")
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.Property<int>("VehicleRole")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_role");

                    b.HasKey("AccidentId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Involves", (string)null);
                });

            modelBuilder.Entity("Aoun.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("QuestionCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("question_code");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionTextAr")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_text_ar");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("question_type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("QuestionId")
                        .HasName("PK__Question__2EC215495087E83F");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("Aoun.Models.QuestionOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("option_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OptionId"));

                    b.Property<string>("OptionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("option_code");

                    b.Property<string>("OptionTextAr")
                        .IsRequired()
                        .HasMaxLength(400)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("option_text_ar");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOption", (string)null);
                });

            modelBuilder.Entity("Aoun.Models.Report", b =>
                {
                    b.Property<int>("AccidentId")
                        .HasColumnType("int")
                        .HasColumnName("accident_id");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("int")
                        .HasColumnName("driver_user_id");

                    b.Property<DateTime?>("ReportTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("report_time")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("AccidentId", "DriverUserId");

                    b.HasIndex("DriverUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Aoun.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aoun.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("int")
                        .HasColumnName("driver_user_id");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicle__...");

                    b.HasIndex(new[] { "LicensePlate" }, "UQ__Vehicle__F72CD56EA546ED93")
                        .IsUnique();

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Aoun.Models.AccidentConflict", b =>
                {
                    b.HasOne("Aoun.Models.Accident", "Accident")
                        .WithMany()
                        .HasForeignKey("AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("Aoun.Models.AccidentReport", b =>
                {
                    b.HasOne("Aoun.Models.Accident", "Accident")
                        .WithOne("AccidentReport")
                        .HasForeignKey("Aoun.Models.AccidentReport", "AccidentId")
                        .IsRequired()
                        .HasConstraintName("FK_Report_Accident");

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("Aoun.Models.AccidentSessionParticipant", b =>
                {
                    b.HasOne("Aoun.Models.Accident", "Accident")
                        .WithMany()
                        .HasForeignKey("AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("Aoun.Models.Answer", b =>
                {
                    b.HasOne("Aoun.Models.Accident", "Accident")
                        .WithMany("Answers")
                        .HasForeignKey("AccidentId")
                        .IsRequired()
                        .HasConstraintName("FK_Answer_Accident");

                    b.HasOne("Aoun.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Answer_Question");

                    b.Navigation("Accident");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Aoun.Models.DriverFeedback", b =>
                {
                    b.HasOne("Aoun.Models.Accident", "Accident")
                        .WithMany("DriverFeedbacks")
                        .HasForeignKey("AccidentId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Accident");

                    b.HasOne("Aoun.Models.Driver", "Driver")
                        .WithMany("DriverFeedbacks")
                        .HasForeignKey("DriverUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Driver");

                    b.Navigation("Accident");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Aoun.Models.Image", b =>
                {
                    b.HasOne("Aoun.Models.Accident", "Accident")
                        .WithMany("Images")
                        .HasForeignKey("AccidentId")
                        .IsRequired()
                        .HasConstraintName("FK_Image_Accident");

                    b.HasOne("Aoun.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("DriverUserId");

                    b.Navigation("Accident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aoun.Models.Involve", b =>
                {
                    b.HasOne("Aoun.Models.Accident", "Accident")
                        .WithMany("Involves")
                        .HasForeignKey("AccidentId")
                        .IsRequired()
                        .HasConstraintName("FK_Involves_Accident");

                    b.HasOne("Aoun.Models.Vehicle", "Vehicle")
                        .WithMany("Involves")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("FK_Involves_Vehicle");

                    b.Navigation("Accident");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Aoun.Models.QuestionOption", b =>
                {
                    b.HasOne("Aoun.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_QuestionOption_Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Aoun.Models.Report", b =>
                {
                    b.HasOne("Aoun.Models.Accident", "Accident")
                        .WithMany("Reports")
                        .HasForeignKey("AccidentId")
                        .IsRequired()
                        .HasConstraintName("FK_Reports_Accident");

                    b.HasOne("Aoun.Models.Driver", "Driver")
                        .WithMany("Reports")
                        .HasForeignKey("DriverUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reports_Driver");

                    b.Navigation("Accident");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Aoun.Models.Accident", b =>
                {
                    b.Navigation("AccidentReport");

                    b.Navigation("Answers");

                    b.Navigation("DriverFeedbacks");

                    b.Navigation("Images");

                    b.Navigation("Involves");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Aoun.Models.Driver", b =>
                {
                    b.Navigation("DriverFeedbacks");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Aoun.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Aoun.Models.Vehicle", b =>
                {
                    b.Navigation("Involves");
                });
#pragma warning restore 612, 618
        }
    }
}
